### ISSUE TITLE
How do I use it with my external IP?

### ISSUE THREAD

**Issue by ghost** [noobswestand/Python-Server-GM-Client#2]
You really did a good job with this code!
But I'm now trying to use an external IP instead of only doing a local server. I port forwarded and I know the server is working with the external IP because I managed to send to him sockets from a Port Checker Tool online. But the GameMaker can't connect to the server. Why is that?

**Comment by noobswestand** [comment]
Are you trying to connect on the same LAN? Or is the computer on a different network?I have been able to port forward and have different people connect.  It might be your computer firewall blocking it, or something else.    On Tuesday, March 17, 2020, 04:03:43 PM CDT, GameMakerStudio2Cracker <notifications@github.com> wrote:  
 
 


You really did a good job with this code!
But I'm now trying to use an external IP instead of only doing a local server. I port forwarded and I know the server is working with the external IP because I managed to send to him sockets from a Port Checker Tool online. But the GameMaker can't connect to the server. Why is that?

**Comment by FlafyDev** [comment]
> Are you trying to connect on the same LAN? Or is the computer on a different network?I have been able to port forward and have different people connect.  It might be your computer firewall blocking it, or something else. On Tuesday, March 17, 2020, 04:03:43 PM CDT, GameMakerStudio2Cracker <notifications@github.com> wrote: You really did a good job with this code! But I'm now trying to use an external IP instead of only doing a local server. I port forwarded and I know the server is working with the external IP because I managed to send to him sockets from a Port Checker Tool online. But the GameMaker can't connect to the server. Why is that? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Turns out I tried connecting to my server from the client in the same network. And my router doesn't support NAT loopback. So from the same network, I need to connect to "localhost".
Thanks for the help!

**Comment by FlafyDev** [comment]
> Are you trying to connect on the same LAN? Or is the computer on a different network?I have been able to port forward and have different people connect.  It might be your computer firewall blocking it, or something else. On Tuesday, March 17, 2020, 04:03:43 PM CDT, GameMakerStudio2Cracker <notifications@github.com> wrote: You really did a good job with this code! But I'm now trying to use an external IP instead of only doing a local server. I port forwarded and I know the server is working with the external IP because I managed to send to him sockets from a Port Checker Tool online. But the GameMaker can't connect to the server. Why is that? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi again, I have another problem.
For some reason, whenever I send from the server a socket with a large buffer(like a 12000~ characters string) to all the clients, on clients that are connected from a different network of the server don't get all the data, just part of it... Clients that are connected to the server from the same network of the server, get all the data.

I made a post about it in StackOverflow: https://stackoverflow.com/q/60744574/10849036
But no buddy answered. Maybe you know what to do? Thanks.
